image: Visual Studio 2015

configuration:
- Debug
- Release

build:
  project: .\win32\VS2010\opus.sln
  parallel: true

after_build:
- 7z a opus-112-win32-build.7z .\win32\VS2010\ .\include

artifacts:
- path: .\opus-112-win32-build.7z

